---
output: html_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

# Research Studies

Here are a table of the flyers for research studies at JHU:

```{r reader, include = FALSE}
library(googlesheets)
library(dplyr)
doc = gs_url("https://docs.google.com/spreadsheets/d/1uFuY9qw92BomzfplDDsh9stnEh1Zc-3AyRvuXZJd0VU/edit#gid=0") 
data = doc %>% 
  gs_read


df = data
df = df %>% 
  mutate(compensation = trimws(compensation),
         compensation = sub("$", "", compensation, fixed = TRUE),
         compensation = sub(",", "", compensation, fixed = TRUE),
         compensation = as.numeric(compensation))
createLink <- function(val) {
  sprintf('<a href="%s" target="_blank" class="btn btn-primary">Link</a>',val)
}
df = df %>% 
  mutate(Flyer = createLink(Flyer)) %>% 
  select(Flyer, Name, compensation,  compensated, sex, phone, phone2, email, email2,  everything()) %>% 
  arrange(desc(compensation)) 

```


```{r dtable}

library(DT)
DT::datatable(df, escape = FALSE, width = "100%",  options = list(
  autoWidth = TRUE,
  paging = FALSE,
  pageLength = 30))
```

# Tables from the Hub

See https://hub.jhu.edu/announcements/students/research-participants-wanted/ for additional information about studies.  Here is the table we have compiled from that data:

```{r dtable_jhu}
page_df = readr::read_rds("page_links_with_info_newlines.rds")
page_df = page_df %>%
  mutate(info = gsub("•", "\n•", info)) %>% 
  select(-page) %>% 
  mutate(link = createLink(link)) %>% 
  select(link, title, summary, everything())
comp = sub(".*(\\$.*)( |[.]|\n)(.*)", "\\1", page_df$info)
comp = strsplit(comp, split = " ")
comp = sapply(comp, dplyr::first)
comp = strsplit(comp, split = "[.]")
comp = sapply(comp, dplyr::first)
comp = strsplit(comp, split = "\n")
comp = sapply(comp, dplyr::first)
comp[!grepl("$", comp, fixed = TRUE)] = NA
comp = sub(",", "", comp)
comp = sub("$", "", comp, fixed = TRUE)
page_df$compensation = comp
page_df = page_df %>% 
  mutate(num_comp = sub("/.*", "", compensation),
         num_comp = as.numeric(num_comp)) %>% 
  arrange(desc(num_comp))
page_df = page_df %>% 
  mutate(
    info = gsub(pattern = "\n\n", replacement = "\n", x = info),
    info = gsub(pattern = "\n", replacement = "<br/>", x = info))
DT::datatable(page_df, escape = FALSE, width = "100%",  options = list(
  autoWidth = TRUE,
  paging = TRUE,
  pageLength = 50))
```
